### PR TITLE
Nonblocking socket

### PR DESCRIPTION
**Pull request by StabbyCutyou**
ping @obrie

### CODE REVIEW

**Comment by obrie** [comment]
My only concern is this note in the blog post referenced:

> However, its worth pointing out that the recommended solution can actually be pretty bad because Ruby’s non-blocking IO methods actually blow Ruby’s global method cache. This approach will be pretty painful to your entire Ruby runtime performance and for larger scale applications it could be deadly.

That blog post references this document @ https://github.com/charliesome/charlie.bz/blob/master/posts/things-that-clear-rubys-method-cache.md:

> Ruby's IO system has a collection of methods that are non-blocking. For example, IO#read_nonblock, IO#readpartial, IO#write_nonblock, Socket#connect_nonblock, Socket#recvfrom_nonblock, Socket#accept_nonblock, and many others.
> 
> In some cases, these methods raise exceptions extended with IO::WaitWritable or IO::WaitReadable. Unfortunately, the exceptions are extended with these modules every time they are raised - invalidating every method cache.

It may not affect us, but I wanted to make sure we spent a moment thinking through that and the alternative solution suggested in the blog post to make sure this was the right direction to take.

**Comment by StabbyCutyou** [comment]
Oh wow, that is... crazy.

Likely, we should wait and see if this turns out to be a problem for us, which will give us some time to look at the alternative approach.

**Comment by obrie** [comment]
That sounds reasonable.  Can you create a backlog issue to revisit this?

**Comment by obrie** [comment]
Looks good

**Comment by StabbyCutyou** [comment]
Closing this to open one rebased on our master

**Pull request closed without merging**
